#!/bin/sh
# Writes docs/evidence.js from facts available at run time.
# Called by `make evidence` only after `make verify` has succeeded in the same
# invocation. Never invents PR URLs or CI status: remote facts come from
# evidence/remote.env, which is written only after the remote action happened.
set -eu

STATUS="${1:-unverified}"
BRANCH=$(git rev-parse --abbrev-ref HEAD)
COMMIT=$(git rev-parse --short HEAD)
NOW=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

PR_URL=""
CI_STATUS="not checked"
REVIEWERS="[]"
if [ -f evidence/remote.env ]; then
  # shellcheck disable=SC1091
  . ./evidence/remote.env
fi

if [ -n "$PR_URL" ]; then PR_JSON="\"$PR_URL\""; else PR_JSON="null"; fi

cat > docs/evidence.js <<EOF
// Generated by scripts/generate-evidence.sh. Do not edit by hand.
window.EVIDENCE = {
  verified: $([ "$STATUS" = "verified" ] && echo true || echo false),
  generatedAt: "$NOW",
  branch: "$BRANCH",
  commit: "$COMMIT",
  prUrl: $PR_JSON,
  ciStatus: "$CI_STATUS",
  commands: [
    { cmd: "make test", result: "$([ "$STATUS" = "verified" ] && echo "passed (lint, typecheck, 10 Vitest tests in Docker)" || echo "not yet run")" },
    { cmd: "make test-e2e", result: "$([ "$STATUS" = "verified" ] && echo "passed (1 Playwright workflow in Docker)" || echo "not yet run")" },
    { cmd: "make verify", result: "$([ "$STATUS" = "verified" ] && echo "passed" || echo "not yet run")" }
  ],
  reviewers: $REVIEWERS
};
EOF
echo "Wrote docs/evidence.js (verified=$STATUS, $BRANCH@$COMMIT)"
